### PR TITLE
Don't try to load events that don't exist

### LINKED ISSUE #26: Error of events I do not use
when somebody bot mentioned it, I wanted it to add a heart emoji.
The system was working but after this operation it gives the console an error. Then the bot was closing.
I used "add reaction" in this system, but I never used the "Message Reaction Added MOD" event on my bot.
This doesn't just happen in this system. For example, such things happen in the "Member Start Streaming" event. Although I never use it on the bot, it gives errors to the console and the bot closes.
This error happened when dbm switched to v12.

Console Error:

Error with the command "Add Reaction", Action #2:
TypeError: Bot.$evts.Message Reaction Added MOD is not iterable
C:\Users\admin\Desktop\Via Bot\events\message_reaction_added_EVT.js:15
      for (const event of Bot.$evts['Message Reaction Added MOD']) {

TypeError: Bot.$evts.Message Reaction Added MOD is not iterable
    at Client.DBM.Events.reactionAdded (C:\Users\admin\Desktop\Via Bot\events\message_reaction_added_EVT.js:15:36)
    at Client.emit (events.js:315:20)
    at MessageReactionAdd.handle (C:\Users\admin\Desktop\Via Bot\node_modules\discord.js\src\client\actions\MessageReactionAdd.js:44:17)
    at Object.module.exports [as MESSAGE_REACTION_ADD] (C:\Users\admin\Desktop\Via Bot\node_modules\discord.js\src\client\websocket\handlers\MESSAGE_REACTION_ADD.js:4:37)
    at WebSocketManager.handlePacket (C:\Users\admin\Desktop\Via Bot\node_modules\discord.js\src\client\websocket\WebSocketManager.js:386:31)
    at WebSocketShard.onPacket (C:\Users\admin\Desktop\Via Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:436:22)
    at WebSocketShard.onMessage (C:\Users\admin\Desktop\Via Bot\node_modules\discord.js\src\client\websocket\WebSocketShard.js:293:10)
    at WebSocket.onMessage (C:\Users\admin\Desktop\Via Bot\node_modules\ws\lib\event-target.js:125:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\admin\Desktop\Via Bot\node_modules\ws\lib\websocket.js:797:20)

Ekran Alıntısı

System SS:
Ekran Alıntısı

Ekran Alıntısı

Ekran Alıntısı

### PR DESCRIPTION
**Pull request by RigidStudios**

### CODE REVIEW

File: events/on_member_role_removed_EVT.js [hunk 1]
```diff
@@ -9,12 +9,13 @@ module.exports = {
...
     const { Bot, Actions } = DBM
     DBM.Events.roleRemoved = async function (oldMember, newMember) {
-      const oldRoles = oldMember.roles
-      const newRoles = newMember.roles
+      if (newMember.roles.cache.size > oldMember.roles.cache.size) return
+      const oldRoles = oldMember.roles.cache
+      const newRoles = newMember.roles.cache
 
       const difference = oldRoles.filter((role) => !newRoles.has(role.id)).first()
-      if (newMember.roles.size > oldMember.roles.size) return
```
Comment (almeidx) [inline events/on_member_role_removed_EVT.js:16]: I believe this should stay?

**Review by almeidx — CHANGES_REQUESTED** [review]

File: events/on_member_role_removed_EVT.js (hunk 1 above)
Comment (RigidStudios) [reply events/on_member_role_removed_EVT.js:16]: Line 12 In the updated document, I moved it up and made it grab `cache`'s size.

**Review by ForceBlood — APPROVED** [review]
Looks good

**Review by almeidx — APPROVED** [review]
